### ISSUE TITLE
The 1.1.2 static linux build does not support dead keys ?

### ISSUE THREAD

**Issue by LGD-Fr** [ricochet-im/buildscripts#1]
I tested the https://ricochet.im/releases/1.1.2/ricochet-1.1.2-static-x86_64.tar.bz2 version on my fedora 23 system and I was unable to type "ê" or "ü" or anything with _dead keys_.

However, the 1.1.2 version I compiled on my system with `git checkout v1.1.2 && qmake-qt5 && make` does not have this problem.

Cf. https://github.com/ricochet-im/ricochet/issues/428

**Comment by special** [comment]
This is indeed a bug with the linux-static builds specifically, but the fix turns out to be part of ricochet's build. Will track progress on https://github.com/ricochet-im/ricochet/issues/60 (in particular, see the solution at https://github.com/ricochet-im/ricochet/issues/60#issuecomment-258316230). Thanks!
