### ISSUE TITLE
mingw-cross fails to compile

### ISSUE THREAD

**Issue by psycik** [ricochet-im/buildscripts#3]
utils.cpp in qttools errors with:
`Error: Range-based loops are not allowed in C++98`

**Comment by special** [comment]
What version of mingw GCC are you using? You won't get very far without C++11 support, if it actually is missing. I tested with:

```
gcc version 6.2.0 20160822 (Fedora MinGW 6.2.0-1.fc24) (GCC) 
```

Anyway, the fix is trivial: just use Qt's `foreach (const QByteArray &line, output.split('\n'))` syntax instead of range-for here:

https://github.com/ricochet-im/buildscripts/blob/master/mingw-cross/0001-windeployqt-Hack-to-use-objdump-for-PE-parsing.patch#L88

Let me know how that goes.

**Comment by special** [comment]
Also, you may need to modify the path hardcoded into that patch:

https://github.com/ricochet-im/buildscripts/blob/master/mingw-cross/0001-windeployqt-Hack-to-use-objdump-for-PE-parsing.patch#L39

This should point to whatever directory contains `libstdc++-*.dll`, `libwinpthread-*.dll`, etc. We need to figure out a way to discover that path automatically.

**Comment by psycik** [comment]
`gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4`
I got it to compile fine after after running the g++ for that file myself adding -std=c++0x then re-running make.
